#!/usr/bin/env python3
"""Regenerate seed_rules_words.sql from the pre-Postgres JSON resources.

rule.json / word.json under migration/data are the files the bot shipped with
before commit d025a2b ("switch to postgres") moved rules and words into the
database; they are recovered from d025a2b^ so the tables can be rebuilt.

Mapping to the schema WordMapper.kt expects:
    rules(id, name, parent)          <- rule.json, keyed by its own id
    words(word, right_word, answer, ruleid) <- word.json, section -> rule id

Rule id 1 ("Все правила") deliberately has no words: getWords treats ruleId = 1
as "every word".
"""

import json
import pathlib
import sys

HERE = pathlib.Path(__file__).parent
DATA = HERE / "data"
OUT = HERE / "seed_rules_words.sql"

# Two words carry a section that no rule declares:
#   "r17м" - Cyrillic м typo'd onto r17 ("ев - ив, лив - чив"), safe to fix.
#   "15"   - single entry "вишен_ка" whose answer field ("_r") is broken too;
#            there is no section 15, so it is dropped rather than guessed.
SECTION_FIXES = {"r17м": "r17"}
SKIP_SECTIONS = {"15"}

DDL = """CREATE TABLE IF NOT EXISTS rules (
    id     INTEGER PRIMARY KEY,
    name   TEXT    NOT NULL,
    parent INTEGER NOT NULL DEFAULT -1
);

CREATE TABLE IF NOT EXISTS words (
    word       TEXT    NOT NULL,
    right_word TEXT    NOT NULL,
    answer     TEXT    NOT NULL,
    ruleid     INTEGER NOT NULL REFERENCES rules (id)
);

CREATE INDEX IF NOT EXISTS words_ruleid_idx ON words (ruleid);
"""


def quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main() -> int:
    rules = json.loads((DATA / "rule.json").read_text(encoding="utf-8"))["data"]
    words = json.loads((DATA / "word.json").read_text(encoding="utf-8"))["word"]

    section_to_id = {rule["section"]: int(rule_id) for rule_id, rule in rules.items()}

    lines = [
        "-- Generated by migration/generate_rules_words_seed.py — do not edit by hand.",
        "-- Rebuilds the rules/words tables from the JSON the bot used before Postgres.",
        "",
        DDL,
        "BEGIN;",
        "",
    ]

    for rule_id, rule in sorted(rules.items(), key=lambda kv: int(kv[0])):
        lines.append(
            "INSERT INTO rules (id, name, parent) VALUES "
            f"({int(rule_id)}, {quote(rule['name'])}, {int(rule['parent'])}) "
            "ON CONFLICT (id) DO NOTHING;"
        )
    lines.append("")

    skipped = []
    kept = 0
    for word in words:
        section = SECTION_FIXES.get(word["section"], word["section"])
        if section in SKIP_SECTIONS or section not in section_to_id:
            skipped.append(word)
            continue
        lines.append(
            "INSERT INTO words (word, right_word, answer, ruleid) VALUES "
            f"({quote(word['word'])}, {quote(word['right_word'])}, "
            f"{quote(word['answer'])}, {section_to_id[section]});"
        )
        kept += 1

    lines.append("")
    lines.append("COMMIT;")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")

    print(f"rules: {len(rules)}")
    print(f"words: {kept} inserted, {len(skipped)} skipped")
    for word in skipped:
        print(f"  skipped {word}", file=sys.stderr)
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
